# Generated by Django 4.1.1 on 2023-04-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('diet_recommendations', models.TextField()),
                ('exercise_recommendations', models.TextField()),
                ('test_recommendations', models.TextField()),
            ],
        ),
    ]
